In [2]:
import torch
import numpy as np

In [3]:
x = torch.arange(12)
x=x.reshape(-1,6)
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [6]:
y=torch.zeros(5,5)
y

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
torch.randn(1,3,2)

tensor([[[-0.4159,  0.4643],
         [-0.7814, -0.6830],
         [ 0.9656, -0.4380]]])

In [10]:
x=torch.arange(12).reshape(-1,4)
y=torch.randn(3,4)
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 1.4047,  0.0129,  0.1018, -0.7471],
         [-1.1451,  0.8045, -0.9998, -1.4616],
         [-0.1801, -1.2858,  0.4109, -0.4362]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  1.4047,  0.0129,  0.1018, -0.7471],
         [ 4.0000,  5.0000,  6.0000,  7.0000, -1.1451,  0.8045, -0.9998, -1.4616],
         [ 8.0000,  9.0000, 10.0000, 11.0000, -0.1801, -1.2858,  0.4109, -0.4362]]))

In [12]:
x==y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
X=torch.arange(12).reshape(2,6)
Y=torch.arange(3).reshape(3,1)
X+Y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

- <font color=red>广播机制要求两个张量在每个维度上的大小要么相同，要么其中一个张量在该维度上的大小为 1。这样，小尺寸的张量会在这个维度上自动扩展（广播）以匹配大尺寸张量的形状

In [16]:
X=torch.arange(12).reshape(1,12)
Y=torch.arange(3).reshape(3,1)
X+Y

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [18]:
a= torch.arange(12, dtype=torch.float32).reshape((1,12))
b=torch.randn(12).reshape(1,12)
before = id(a)
a += b
id(a) == before

True

In [20]:
A=a.numpy()
B=torch.tensor(A)
type(A),type(B),B.size()

(numpy.ndarray, torch.Tensor, torch.Size([1, 12]))

In [22]:
b=torch.tensor([3])
b.item(),float(b)

(3, 3.0)

_______


In [25]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [35]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [79]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [71]:
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


___


In [117]:
A=torch.arange(120).reshape(2,5,3,4)


In [115]:
A=torch.arange(12,dtype=torch.float32).reshape(3,4)
B=A
id(A)==id(B)

True

In [184]:
A=torch.arange(24,dtype=torch.float32).reshape(2,3,4)
A,A.shape,A.dtype # 先看形状

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 torch.Size([2, 3, 4]),
 torch.float32)

In [194]:
A.cumsum(dim=0),A.sum(dim=1),A.sum(dim=2)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 14., 16., 18.],
          [20., 22., 24., 26.],
          [28., 30., 32., 34.]]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]))

In [238]:
x=torch.arange(12,dtype=torch.float32)
y = torch.randn(12, dtype = torch.float32)
torch.dot(x,y)

tensor(-6.4209)

In [247]:
# 尝试矩阵乘列向量
A=torch.arange(12).reshape(4,3)
x=torch.arange(3)
A,x,torch.mv(A,x)

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([0, 1, 2]),
 tensor([ 5, 14, 23, 32]))

In [253]:
# 矩阵乘法
C=torch.arange(12,dtype=torch.float32).reshape(3,4)
D=torch.ones(8,dtype=torch.float32).reshape(4,2)
torch.mm(C,D)

tensor([[ 6.,  6.],
        [22., 22.],
        [38., 38.]])

In [267]:
torch.norm(C),C.abs().sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(22.4944),
 tensor(66.))

In [283]:
A=torch.ones(2,3,4)
A.shape,A.sum(axis=0,keepdim=True).shape

(torch.Size([2, 3, 4]), torch.Size([1, 3, 4]))

_______

In [318]:
import torch
x = torch.arange(4.0,requires_grad=True)
x.grad # # 默认为None

In [320]:
y=2*torch.dot(x,x)
y.backward()
x.grad,x.grad==4*x

(tensor([ 0.,  4.,  8., 12.]), tensor([True, True, True, True]))

In [330]:
# 计算另一个函数
x.grad.zero_()  #在 PyTorch 中，zero_()是一个很常用的方法。它主要用于将张量（Tensor）中的元素全部设置为 0。 例如，如果你有一个张量x = torch.tensor([1, 2, 3])，执行x.zero_()后，x的值就会变为torch.tensor([0, 0, 0])
y=sum(x)
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [332]:
help(torch.ones)

Help on built-in function ones in module torch:

ones(...)
    ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

    Returns a tensor filled with the scalar value `1`, with the shape defined
    by the variable argument :attr:`size`.

    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.

    Keyword arguments:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, uses the curre